### PR TITLE
fix: update alert example with proper email notifier reference

### PR DESCRIPTION
**Pull request by filipgolonka**

### CODE REVIEW

**Review by SaaldjorMike — APPROVED** [review]
Thanks!

**Comment by filipgolonka** [comment]
@SaaldjorMike I am not sure if other examples should be updated as well

**Comment by SaaldjorMike** [comment]
@filipgolonka Ah yes, good point. The other `humio_alert` resources that refers to notifier ID's should also be updated, similar to what was done in this PR.

**Comment by filipgolonka** [comment]
Ok, I will create another PR with this, thanks!

**Comment by filipgolonka** [comment]
Too late, I can see you did it already 😅

**Pull request merged**
